language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
script: npm test # Here you could also run the build step of your application
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --public --token $NOW_TOKEN --regions bru -e DATABASE=@rsfa_db_access
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --public --token $NOW_TOKEN --regions bru -e DATABASE=@rsfa_db_access && DeploymentID=$(now ls 2>/dev/null| egrep -iwo 'rsfaperfx-.*.now.sh') now alias  --token $NOW_TOKEN $DeploymentID rsfaperfx
    skip_cleanup: true
    on:
      master: true